### ISSUE TITLE
Implement Email Notifications for Test Case Generation

### ISSUE THREAD

**Issue by ank1traj** [WebSorcery/testcase-generator#10]
Implement an email notification system to automatically send emails to users once test cases have been generated. This will involve integrating an email service into our backend to notify users about the completion of the test case generation process.

**Comment by singhcoder694** [comment]
I would like to work on this... @ank1traj

**Comment by ank1traj** [comment]
Assigned @singhcoder694

**Comment by singhcoder694** [comment]
Users email would be needed , so from where on website we would get ?

**Comment by ank1traj** [comment]
We've to integrate the authentication module @singhcoder694. Already, created the issue but no one is working right now. If you want then you can work on that issue and then come to this. 

https://github.com/WebSorcery/testcase-generator/issues/9

**Comment by singhcoder694** [comment]
@ank1traj I have made PR for #9 , after your final review I can start to work on this issue so that final integration can be done....

**Comment by singhcoder694** [comment]
In this mail should reach to user in fail cases also.... i.e. if any error comes that should also reach in form of erro otherwise success message would reach user. Is it @ank1traj

**Comment by ank1traj** [comment]
Yes @singhcoder694

**Comment by singhcoder694** [comment]
May I do this in typescript since there is nothing available for mailing using js on docs.

**Comment by ank1traj** [comment]
There are @singhcoder694. See nodemailer.

**Comment by singhcoder694** [comment]
> There are @singhcoder694. See nodemailer.

Got it sir thanks for this I was doing it using resend🙂

**Comment by ank1traj** [comment]
@singhcoder694 few issues I found while testing the feature. Do you want to work on the same?

1. Even if the email is not sent it's getting a success message about `Values generated successfully and mail sent!`. It shouldn't be like this. 
2. Email not sent error is coming twice.
3. Mail is not getting sent. Getting this error in API call `https://testcase-generator-rose.vercel.app/api/confirm`

**Comment by singhcoder694** [comment]
@ank1traj 
1.) That I will solve within minutes.
2.) I will solve it by tommorrow.
3.) It was coming but few times maybe due to call limit. But mostly mail was sent.

**Comment by ank1traj** [comment]
Sure, take your time. And, please have a look because due to call limit it should give 429 not 405. There is some issue in the API. I will check it too and will figure out why it's giving 405.

**Comment by singhcoder694** [comment]
<img width="395" alt="Screenshot 2023-12-25 170446" src="https://github.com/WebSorcery/testcase-generator/assets/114601400/b83154af-94ea-4d1d-823b-ce16059d9812">
<img width="394" alt="Screenshot 2023-12-25 170455" src="https://github.com/WebSorcery/testcase-generator/assets/114601400/097dd82d-030e-455d-a1eb-2d3328676179">
Look at these I sent to myself while testing...

**Comment by ank1traj** [comment]
Can you do one thing while working on this? Try with both zoho and gmail and also with attachment and without attachment.

**Comment by singhcoder694** [comment]
Hmm, Ok sir got it I will try to do it by tommorow... 🫡

**Comment by singhcoder694** [comment]
@ank1traj resolved error by pr #38

**Comment by ank1traj** [comment]
@singhcoder694 No, it's still not fixed. let's sit together tomorrow and work on this and fix this asap.

**Comment by ank1traj** [comment]
@singhcoder694 Fixed the issue.
