### ISSUE TITLE
Integrate OAuth Login using Clerk

### ISSUE THREAD

**Issue by ank1traj** [WebSorcery/testcase-generator#9]
Integrate OAuth-based login functionality into our system using Clerk, ensuring secure and streamlined user authentication. This issue involves setting up OAuth authentication mechanisms and incorporating Clerk's services for user login and management.

**Comment by singhcoder694** [comment]
@ank1traj I would like to do this.... It would be helpful for me also as by this I would learn about Oauth and Clerk. So I would like to work on this first...

**Comment by ank1traj** [comment]
Sure, go ahead
